### ISSUE TITLE
release v0.16.0 missing static assets

### ISSUE THREAD

**Issue by SkyperTHC** [praetorian-inc/noseyparker#100]
Missing static linux/x86_64 assets for v0.16.0 on the release section (only contains the source packages). Auto-install scripts are failing which rely on the static release binary. Static release bins were available for all previous versions. Please add ❤️

**Comment by Azathothas** [comment]
@bradlarsen 

Unfortunately, the released binary is still dynamic:
```bash
--> https://github.com/praetorian-inc/noseyparker/releases/download/v0.16.0/noseyparker-v0.16.0-x86_64-unknown-linux-gnu.tar.gz
file noseyparker
noseyparker: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=fe547c8ef316f1385e0628159c7ad0e49ad45a48, for GNU/Linux 3.2.0, with debug_info, not stripped
```

To build static: 

```bash
!# cross
  git clone --filter "blob:none" "https://github.com/praetorian-inc/noseyparker" && cd "./noseyparker"
  cargo install -f cross
  export TARGET="x86_64-unknown-linux-musl" ; rustup target add "$TARGET" ; export RUSTFLAGS="-C target-feature=+crt-static"
  sed '/^\[profile\.release\]/,/^$/d' -i "./Cargo.toml" ; echo -e '\n[profile.release]\nstrip = true\nopt-level = "z"\nlto = true' >> "./Cargo.toml"
  cross build --target "$TARGET" --release

!# cargo
  git clone --filter "blob:none" "https://github.com/praetorian-inc/noseyparker" && cd "./noseyparker"
  export TARGET="x86_64-unknown-linux-gnu" ; rustup target add "$TARGET" ; export RUSTFLAGS="-C target-feature=+crt-static"
  sed '/^\[profile\.release\]/,/^$/d' -i "./Cargo.toml" ; echo -e '\n[profile.release]\nstrip = true\nopt-level = "z"\nlto = true' >> "./Cargo.toml"
  cargo build --target "$TARGET" --release 

---
  file "./target/$TARGET/release/noseyparker-cli"
  ./target/x86_64-unknown-linux-musl/release/noseyparker-cli: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped
```

**Comment by bradlarsen** [comment]
@Azathothas @SkyperTHC

Perhaps I read this initial issue too quickly — I thought you were asking simply for the prebuilt releases. Indeed, the prebuilt Nosey Parker releases are dynamically linked.

The releases always have been dynamically linked, actually. However, prior to v0.14.0, the releases were simply single-file zipped binaries. Starting in v0.14.0, the releases are tarballs with some added directory structure and additional assets (such as shell completion scripts).

I've wanted to provide statically-linked binaries from the start (#58). However, I never figured out the proper incantation to `cargo` to make that work; the build would always fail somewhere when building native-code dependencies with complicated CMake scripts that interrogate the environment (vectorscan, zlib, ...).

However, the invocations you share above _do_ seem to result in a static binary! It seems like the `RUSTFLAGS="-C target-features=+crt-static"` does the trick. Thank you! I will experiment with this more, and may include statically-linked binaries for future releases. (It would help with the use case of running on older LInux systems, like in #58.)

Note, however, that the Nosey Parker releases will continue to be distributed as tarballs in the future (and not as zipped single binaries). The open-source `noseyparker` _does_ run correctly at present when pulled out of the release directory tree, but I am not promising to preserve that deployment scenario.

**Comment by bradlarsen** [comment]
P.S. @SkyperTHC Is it this project that's using Nosey Parker releases, or something else?

https://github.com/hackerschoice/segfault

I'm just curious to hear about how Nosey Parker is getting used 😎
