### ISSUE TITLE
Stabilize the JSON format

### ISSUE THREAD

**Issue by munntjlx** [praetorian-inc/noseyparker#101]
**Is your feature request related to a problem? Please describe.**
We are using noseyparker as part of a 'defect dojo' secret tracking and discovery process. We use the jsonl format, but it seems to change arbitrarily between even minor versions.  This causes us to have to modify our parser scripts (for defect dojo) since our unit tests fail when the JSON format changes.

**Describe the solution you'd like**
Can we stabilize the json format or agree to only change it on x versions? This would make derivitave works or programs having a 'stable' base upon which to build. 

**Describe alternatives you've considered**
Perhaps 'we change the json format every .2 or .4 increments of a new version? Or an 'odd vs 'even' which gives us some stability on the JSON format?

**Additional context**
Just to note this is a GREAT project and we really appreciate the work you are doing!

**Comment by bradlarsen** [comment]
P.S. @munntjlx out of curiosity, are your defect dojo parser scripts proprietary, or are they part of the DefectDojo project?

**Comment by munntjlx** [comment]
THey will eventually be part of the main project. Tanvi is working on these which we hope to mainline once they get around to importing the parser.

________________________________________

**Comment by bradlarsen** [comment]
Anyway, aside from trying hard to not change the JSON output between releases, the place to start with stabilization is to write a schema and validate against that (at least in testing): #72.

**Comment by bradlarsen** [comment]
@munntjlx there are more changes to the JSON report coming in the next release (#122). Some fundamentals have changed in the Nosey Parker data model that require some visible changes to the JSON report format.

I'm hoping that these changes are the last major ones, and that future format changes will be infrequent and involve only adding new fields.

I'm also hoping to put together a JSON Schema definition of the report format for the next release. This should help both with documentation of the format and also help with identifying changes of that format.

**Comment by munntjlx** [comment]
Thanks for the heads up. We have been standardizing on 'specific' versions to help reduce the workload associated with schma changes. A json schema would go a long way for helping us to 'stabilize' final version formats.

Thomas

________________________________________

**Comment by munntjlx** [comment]
Our Noseyparker decoder has been added to Defect Dojo Main Project. Probably need to get it beyond v0.16

**Comment by munntjlx** [comment]
Additions would be preferable!

________________________________________
