### ISSUE TITLE
Add Homebrew package

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#120]
Nosey Parker should be available in [Homebrew](https://brew.sh/) for macOS.

To write an appropriate formula for Nosey Parker, one might crib other Rust command-line tools that are available in Homebrew, such as [ripgrep](https://github.com/Homebrew/homebrew-core/blob/master/Formula/r/ripgrep.rb).

Note that Nosey Parker's release-building process is a little different than ripgrep's, using a [wrapper shell script](https://github.com/praetorian-inc/noseyparker/blob/91b734dd7ecf30550dbb47f9989588332b9b3f0a/scripts/create-release.zsh) that assembles a release directory.

**Comment by bradlarsen** [comment]
Oh, @p-linnane added a Homebrew formula a few days ago! It looks like the recipe even installs the shell completion scripts:

https://github.com/Homebrew/homebrew-core/commit/ffbe124f42373902d371c7e438a425d11bb534b5

The only thing to change there, possibly, is to `cargo install` with `--features release`, which is a Nosey Parker-specific feature that compiles out `trace`-level log messages.

**Comment by p-linnane** [comment]
Hi 👋. I'm a Homebrew maintainer and security practitioner. A personal project of mine is to try and get more security-related software into homebrew-core. Glad this was helpful; I wasn't aware of this open issue. Happy to review a PR to add `--features release` if it helps you all.

**Comment by bradlarsen** [comment]
Thanks for the integration @p-linnane!
