### ISSUE TITLE
trouble compiling on amazon linux 2 (with gcc10) and graviton arm

### ISSUE THREAD

**Issue by munntjlx** [praetorian-inc/noseyparker#133]
**Describe the bug**
I used to be able to compile on amazon linux 2 after installing gcc10, but now I get the following error:

```ini

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Warning at CMakeLists.txt:178 (message):
    Something went wrong determining gcc tune:
    -mtune=armv8.2-a+crypto+fp16+rcpc+dotprod+ssbs not valid, falling back to
    -mtune=native


  CMake Error at CMakeLists.txt:264 (message):
    A minimum of g++ 9 is required for C++17 support


  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1
```
I am running gcc version 10.5: and g++ version 10.5:

```bash
root@ip-10-148-161-36 /u/s/noseyparker (main)# gcc --version
gcc (GCC) 10.5.0 20230707 (Red Hat 10.5.0-1)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@ip-10-148-161-36 /u/s/noseyparker (main)# cpp --version
cpp (GCC) 10.5.0 20230707 (Red Hat 10.5.0-1)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@ip-10-148-161-36 /u/s/noseyparker (main)# g++ --version
g++ (GCC) 10.5.0 20230707 (Red Hat 10.5.0-1)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

  **To Reproduce**
install amazon linux 2, install gcc 10.5 from amazon extras, install rust using rustup to version 1.76

**Expected behavior**
System gives error messages as noted in output above.  Please note my os verison as reported by uname `linux 5.10.209-.amzn2.aarch64 #1 SMP Tue Feb 13 18:46:45 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Screenshots**

**Output of `noseyparker --version`**

**Additional context**
The 'older' version used to compile.

**Comment by munntjlx** [comment]
NM it seems to compile when its in /src for some wierd reason! So I guess you can ignore?

**Comment by munntjlx** [comment]
might be useful for people using in /usr/src or with broken gcc installed.....

**Comment by bradlarsen** [comment]
@munntjlx I'm not sure what's going on here. All I can say is that I have not tried building Nosey Parker on Linux for ARM, only for x86_64. It ought to work in principal, but there may be rough edges.

What did you have to do to get the build working?

**Comment by munntjlx** [comment]
Funnily enough just changing the directory and recloning the repo.

I suspect it was looking at some things that were patched (I had to horribly hack the os to get things to work due to the extreme age of the os!). I can provide you a working RPM/Binary if you are interested.

thomas

________________________________________
