### ISSUE TITLE
Error: Failed to initialize resource limits: Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by kobenys** [praetorian-inc/noseyparker#170]
Noseyparker scan action produce this result -
`./noseyparker scan --datastore data .`
`Error: Failed to initialize resource limits: Operation not permitted (os error 1)`

Without scan action it starts well -
`./noseyparker `
`Nosey Parker is a command-line program that finds secrets and sensitive information in textual data and Git history.`

`Usage: noseyparker [OPTIONS] <COMMAND>`
`...`

**Comment by bradlarsen** [comment]
@kobenys thanks for the report! What platform are you running on?


Adjusting the resource limits — specifically, increasing the open file limit — is done early on to avoid possible crashes later when using a high degree of parallelism and working with a large number of inputs. It's not _essential_ to Nosey Parker operation.

I'll fix this. If attempting to adjust the resource limits at startup fails, a warning should be printed and the operation should attempt to continue on.

**Comment by bradlarsen** [comment]
This is fixed on `main` now, and will be included in the next Nosey Parker release (v0.18.0, in the next several weeks). From there, it should get picked up in Homebrew.
