### ISSUE TITLE
[Bug] `--ignore` flag doesn't works for git url and local directory input

### ISSUE THREAD

**Issue by bugbaba** [praetorian-inc/noseyparker#178]
Hi Team,

**Describe the bug**
The `--ignore` flag for `scan` module doesn't works for git url and local directory input.

**To Reproduce**
With git-url:
Log: https://gist.github.com/bugbaba/ff514ed795731e12b0c3a87031ca801e
```css
noseyparker scan --ignore noseyparker_exclude.txt --git-url https://github.com/bugbaba/noseyparker_test -v -v -v
```

With same repo cloned locally:
Log: https://gist.github.com/bugbaba/0cfd2a1e5603ae1b68710aef7ac11e78
```css
noseyparker scan --ignore noseyparker_exclude.txt noseyparker_test/ -v -v -v
```

**Expected behavior**
The file passed with `--ignore` flag should be parsed and the files mentioned in it should not be scanned. 

**Actual behavior**
The ignore file contains `cdk.json` that should be ignore and shouldn't be searched. But still findings are found in the file.
The file passed with `--ignore` flag is not even parsed for git-url input. For the local directory input the file is parsed but still its failing to avoid the files specified.

**Screenshots**
![image](https://github.com/praetorian-inc/noseyparker/assets/29960776/8e13d6da-396f-4d32-a0bb-ad7a371ec51e)
![image](https://github.com/praetorian-inc/noseyparker/assets/29960776/87df2883-7a60-41a8-86b2-3476d82449ec)

**Output of `noseyparker --version`**
```
noseyparker 0.18.0-dev

Build Configuration:

    Build Timestamp:    2024-04-22T06:19:23.665917778Z

    Commit Timestamp:   2024-04-19T17:51:15.000000000-04:00
    Commit Branch:      main
    Commit SHA:         4d9faba40eaabb9999fd85779e323d24a3e3f6cf

    Cargo Features:     disable_trace,log,release
    Debug:              false
    Optimization:       3
    Target Triple:      x86_64-unknown-linux-gnu

Build System:

    OS:                 Ubuntu
    OS Version:         Linux 22.04 Ubuntu

    CPU Vendor:         AuthenticAMD
    CPU Brand:          AMD EPYC 7B13
    CPU Cores:          8

    rustc Version:      1.77.2
    rustc Channel:      stable
    rustc Host Triple:  x86_64-unknown-linux-gnu
    rustc Commit Date:  2024-04-09
    rustc Commit SHA:   25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04
    rustc LLVM Version: 17.0

```
--
Best Regards,
@bugbaba

**Comment by bradlarsen** [comment]
@bugbaba Thanks for the detailed report. Would you also share what's in the `noseyparker_exclude.txt` file that you are using?

**Comment by bugbaba** [comment]
Hi @bradlarsen, Thank you for looking into this. I currently only have `cdk.json` in it as I am trying to understand and make this work.

**Comment by bradlarsen** [comment]
@bugbaba Oh, I see. I think what you are encountering here is the impact of #17: in Nosey Parker currently, the path-based ignore rules are not used at all when scanning history in Git repositories.

**Comment by bugbaba** [comment]
Sorry, I should have checked the open issues.

**Comment by bradlarsen** [comment]
> Sorry, I should have checked the open issues.

No problem! I appreciate the detailed bug report regardless!
