### ISSUE TITLE
Add support for JSON output format for report

### ISSUE THREAD

**Issue by Yoshi325** [praetorian-inc/noseyparker#31]
Looks like it might have gotten forgotten. The readme and help mentions it, but attempting to use it produces:

```
Error: The `report` command currently only supports the `human` output format.
Support for other formats is coming soon.
```

**Comment by Coruscant11** [comment]
Weird, because `noseyparker report --datastore DATASTORE_FILE_PATH --format json` works for me. :thinking:

**Comment by bradlarsen** [comment]
@Yoshi325 JSON format is indeed supported. Perhaps you are running an old version of Nosey Parker?

What does `noseyparker -V` say?

**Comment by Yoshi325** [comment]
🤦‍♂️ my clone was back at commit 9828e04bdeab60f74763ec23240ff8fdc145a8d4 (so `noseyparker -V` returns `noseyparker 0.10.0`)

A fetch+pull and rebuild gives me a version that supports it.

Sorry for the noise. And thank you very much for your help.
