### ISSUE TITLE
Error: Failed to enumerate GitHub repositories (SSL/TLS Cert Issues)

### ISSUE THREAD

**Issue by Luct0r** [praetorian-inc/noseyparker#38]
Hello I'm probably doing something wrong here, but when I run NoseyParker I'm getting errors related to SSL certificates. When I search for solutions, most mention corporate firewalls or importing CA certificates - both of which seem too involved given I'm running this on a home network and it's trying to connect to `api.github.com` - any help/suggestions would be appreciated.

![image](https://user-images.githubusercontent.com/43627224/224443848-a55dea4a-8b35-4726-82f3-d517662bf3f3.png)

**Comment by bradlarsen** [comment]
I've not seen this one before — thanks for the report!

I see the same behavior when I try with the `ghcr.io/praetorian-inc/noseyparker:latest` Docker image! I'm running on a macOS base system.

The network request you are seeing is being made toward the beginning of the `scan` command execution, to figure out which repositories are visible for your username (`--github-user luct0r`). After that step, and after cloning the repositories, Nosey Parker shouldn't be touching the network at all.

If you `docker pull ghcr.io/praetorian-inc/noseyparker:edge`, and try with that, does the command work for you? (It does for me.)

**Comment by Luct0r** [comment]
Yeah for sure, thanks for the awesome tool! 

Hmm interesting, yes running with `edge` seems to work fine. I thought maybe it could be the docker image and something to do with the `ca-certificates` package since that was mentioned in some of the solutions I found online, but wasn't sure how to troubleshoot that - either way, glad it's working!

Appreciate the help :D

**Comment by bradlarsen** [comment]
I think the issue was that the Docker image with the 0.12.0 tag is too minimal, and is inadvertently missing the 'git' binary and 'ca-certificates' package. I added those to the Docker image, which seems to have fixed this. Definitely a bug.

Thanks for reporting!

**Comment by bradlarsen** [comment]
Fixed by ba067f7364254c5ea7c0b3a8525bd8fc73cdaea4, which added the `git` binary (and indirectly, the `ca-certificates` packages) to the Docker image.
