### ISSUE TITLE
Provide prebuilt Docker images for ARM

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#39]
The Docker images that are currently build in GitHub Actions are built only for x86_64. When someone runs one of these on a different architecture, such as ARM, some kind of binary translation or runtime emulation is performed to get the image running.

It would be better if instead of relying on emulation, Nosey Parker provided multi-architecture Docker images.

**Comment by bradlarsen** [comment]
It's possible to build multi-platform Docker images even on one system (Docker will fall back to QEMU). But this introduces its own complications, and is not a trivial switch.

Some reference materials:
- https://docs.docker.com/build/ci/github-actions/test-before-push/
- https://www.docker.com/blog/multi-platform-docker-builds/
- https://docs.docker.com/build/building/multi-platform/

I have experimented with building a `linux/arm64` image on an x86_64 machine, and the final image seems to work, but it takes a couple hours to build under QEMU.

**Comment by vogler** [comment]
Not working for me on an M1 MBA:

```
$ docker pull ghcr.io/praetorian-inc/noseyparker:latest
6a885bf964f3: Download complete
6bbc39bf4edf: Download complete
e146b6dbe4e0: Download complete
14726c8f7834: Download complete
18562a0474e4: Download complete
d94107639151: Download complete
ghcr.io/praetorian-inc/noseyparker:latest
```

![image](https://github.com/praetorian-inc/noseyparker/assets/493741/53061df1-c6d3-4834-8cec-572fd3f5cfb7)

**Comment by vogler** [comment]
It's commented out while the readme says there's an ARM64 image:
https://github.com/praetorian-inc/noseyparker/blob/98a91762fa4e48a5fb95a8ab55ddaadab42bfdf1/.github/workflows/docker-image.yml#L23

Did the build also take hours on GitHub?
https://github.com/vogler/free-games-claimer/blob/main/.github/workflows/docker.yml - here I have ~16min for a multi-platform 1.36GB Ubuntu image (and much less with cache).

You could also add a cron workflow and build multi-platform at night if it takes too long for your taste.

**Comment by bradlarsen** [comment]
Thanks for the report, @vogler. Indeed, the Docker image is not being tagged as intended: the `latest` tag is supposed to point to the latest stable release, and `edge` points to the latest build from the `main` branch.

The multiplatform images are there for releases, but the tags are not right. I will fix this.

**Comment by bradlarsen** [comment]
@vogler regarding the multi-hour Docker builds, yes, that's what I have observed. I think most of the time goes to building a few big native library dependencies under qemu. I will take a look at your reference! I'd love for it to be fast enough to build the multiarch Docker image on every commit.

**Comment by vogler** [comment]
> I think most of the time goes to building a few big native library dependencies under qemu.

Could try to split building these in separate layers to have them cached if they don't change often.

**Comment by bradlarsen** [comment]
@vogler There are 2 different GitHub Actions workflows that generate Docker images for Nosey Parker:

- https://github.com/praetorian-inc/noseyparker/blob/main/.github/workflows/docker-image.yml
- https://github.com/praetorian-inc/noseyparker/blob/main/.github/workflows/release-artifacts.yml

The second one builds the multi-platform image. The first one was _supposed_ to build just the image with the `edge` tag for x86_64, but it happened to _also_ be tagging the images it built with `latest` and with release tags, hence clobbering the multiplatform images.

I have fixed this issue of bungled tags, so it should not be an issue going forward. I will also see if I can manually fix the release tag for the older releases (v0.14.0, v0.13.0), so they refer to the intended multi-platform images.

**Comment by bradlarsen** [comment]
> > I think most of the time goes to building a few big native library dependencies under qemu.
> 
> Could try to split building these in separate layers to have them cached if they don't change often.

Yes, this is a perennial problem, keeping build speeds up!

Many months ago there was additional caching for rust dependencies when building Docker images in Nosey Parker's GH actions. But that was challenging to maintain (obnoxious technical reasons involving Cargo, GH Actions caching, and Docker), and after restructuring the Nosey Parker code to be split into several internal crates, it became too much to keep up with. There is certainly room for build-time improvements in Nosey Parker.

**Comment by bradlarsen** [comment]
@vogler I have updated the `v0.14.0` and `latest` tags for the Docker image. They should now correctly point at the intended multi-platform image that supports both ARM64 and AMD64:

https://github.com/praetorian-inc/noseyparker/pkgs/container/noseyparker/119700654?tag=v0.14.0
https://github.com/praetorian-inc/noseyparker/pkgs/container/noseyparker/119700654?tag=latest

Please let me know if you have further trouble with this. Thanks again for the report 😎
