### ISSUE TITLE
Support older versions of Linux with prebuilt release binaries

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#58]
@bradlarsen Can we please provide a `musl` binary as well?

I get the following GLIB error when trying to run noseyparker on Ubuntu 20:

```
❯ noseyparker
noseyparker: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by noseyparker)
noseyparker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by noseyparker)
noseyparker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by noseyparker)
noseyparker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by noseyparker)
```

I seem to have GLIB 2.31:

```
❯ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

_Originally posted by @dufferzafar in https://github.com/praetorian-inc/noseyparker/issues/28#issuecomment-1584766119_

**Comment by bradlarsen** [comment]
The issue here is that Nosey Parker is currently built using glibc on Linux, and links against a relatively new version of glibc in the prebuilt release binaries.

A couple options:
- Figure out how to do a totally static link of Nosey Parker
- Create the prebuilt release binaries on an older Linux machine with an older glibc version

The first option may be a bit tricky due to building `vectorscan` from source (big C++ library), but the binary at the end would be most versatile (no runtime dependencies!)

The second option would be simpler to implement (solely a release engineering task: build on an older machine), and would ameliorate the problem, but not totally fix it (like if someone wanted to run on an RHEL7 machine).

**Comment by mas0nd** [comment]
Even some current distros lack the glibc support necessary to execute the release binaries. Running into this issue on Debian 11 right now.

**Comment by bradlarsen** [comment]
I investigated static linking via musl for Nosey Parker.

In an ubuntu 22.04 environment, I had to `apt install` a few `musl`-related packages, and I had to `ln -s /bin/g++ /bin/musl-g++` (cribbed from https://github.com/emk/rust-musl-builder/issues/53).

Then, I had to add the `musl` toolchain to my Rust tools installation:
```
$ rustup target add x86_64-unknown-linux-musl
```

Finally, I tried building:
```
cargo build --target x86_64-unknown-linux-musl
```

I get linker errors at the final linking step for `noseyparker`, like this:
```
...
  = note: /usr/bin/ld: /root/noseyparker/target/x86_64-unknown-linux-musl/debug/deps/libvectorscan_sys-9b706b0b2c08c4c0.rlib(ng_cyclic_redundancy.cpp.o): undefined reference to symbol '__libc_single_threaded@@GLIBC_2.32'
          /usr/bin/ld: /lib/x86_64-linux-gnu/libc.so.6: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `noseyparker-cli` (bin "noseyparker") due to previous error
```

I tried adding linker dependencies to explicitly pull in `c_nonshared` and `c` (cribbed from https://github.com/ziglang/zig/issues/11137), but that did not fix this issue.

I'm not sure what would be involved to fix this.

**Comment by dufferzafar** [comment]
Conceptually, noseyparker shouldn't be much different than ripgrep right? Scan a bunch of files for some regex patterns. Can we look into how they create musl binaries? They'd probably even have a GitHub Action that would automate it all?

**Comment by bradlarsen** [comment]
Yeah, I've looked at what ripgrep does before.

The difficulty for Nosey Parker is the `vectorscan` library (a fork of Hyperscan that supports additional platforms). It's a big C++ codebase that does _very_ fast regex matching. I have yet to figure out how to get that to link against musl.

**Comment by bradlarsen** [comment]
Yeah, Nosey Parker uses a hybrid regex matching scheme: vectorscan (a fork of [Hyperscan](https://github.com/intel/hyperscan)) is used to simultaneously match for _all_ the regex rules on an input at once. Then, to handle its limitations (like lack of capture groups and lack of start-of-match information), the Rust `regex` crate is used to do a second-stage match and gather that missing information.

This complicated two-stage matching approach is much faster than trying to use a traditional regex engine (like rust `regex) directly—probably multiple orders of magnitude, especially as the number of rules grows.

**Comment by dufferzafar** [comment]
One of the things I've done in the past is using an OLD box to build binaries. I basically go to the oldest RHEL box I can find (which would have an old GLIBC) and then build rust apps (without musl) there. 

The binary then works on my Ubuntu machine as well.

**Comment by bradlarsen** [comment]
Yeah, building on an old system is a good idea! I plan to at least do that for the next release, if I can't figure out the static linking story.

I had some luck recently building Nosey Parker on an RHEL 7 machine. That was a hassle (e.g., had to build a new cmake from source), but I was able to get it working.

**Comment by munntjlx** [comment]
I did manage to get noseyparker to build on an alpine current, see my dockerfile PR for the list of things I installed.

**Comment by bradlarsen** [comment]
Note that the Linux releases currently are built on Ubuntu 20.04, which is the oldest Linux version easily available in hosted GitHub Actions runners. Additionally, the Docker images are built using a base image built on top of Debian 12, which was the oldest one I could easily get Nosey Parker building with.

Closing this one in favor of #103 — if we could produce statically-linked releases, we would almost entirely sidestep this problem.
