### ISSUE TITLE
Bash/Fish/Zsh completions?

### ISSUE THREAD

**Issue by munntjlx** [praetorian-inc/noseyparker#67]
I could help debug on these. would be very nice to have these.

**Comment by bradlarsen** [comment]
Yes, having shell completions for Nosey Parker would be nice.

One approach would be to use the `clap_complete` crate to automatically generate completions: https://docs.rs/clap_complete/latest/clap_complete/generator/fn.generate.html. This could be exposed as an additional subcommand, such as `noseyparker shell-completions --shell SHELL`, which would emit the completion script for the requested shell.

**Comment by munntjlx** [comment]
That would be wonderful. Just let me know when the PR is done and I can test for you! I can test fish shell and bash.

**Comment by Coruscant11** [comment]
Hello @bradlarsen,
I worked quickly on this PR for fun if you don't mind. 
I opened the PR : #76 

@munntjlx Feel free to test !
Thank you everyone

**Comment by bradlarsen** [comment]
This is merged back now. Thanks @Coruscant11 :).

@munntjlx let us know if you run into any problems with the new `noseyparker shell-completions` command.

**Comment by munntjlx** [comment]
Wow fancy, you do bash, elvish, fish, powershell AND zsh!
