### ISSUE TITLE
Investigate switching global allocator to mimalloc

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#81]
Using `musl` instead of `glibc` when building Nosey Parker results in a significant drop in scan performance, presumably due to the allocator implementation in `musl` not supporting threaded workloads very well (see [here](https://www.linkedin.com/pulse/testing-alternative-c-memory-allocators-pt-2-musl-mystery-gomes/)).

It may be possible to sidestep this by using a different global allocator in Nosey Parker. In particular, it appears that `jemalloc` does not build with `musl`. But [`mimalloc`](https://github.com/microsoft/mimalloc) _does_ build there, and there is a [Rust crate](https://crates.io/crates/mimalloc) for it already.

Is it easy to switch Nosey Parker to use `mimalloc` as its global allocator?

How does switching impact performance of native-code builds? How does it affect performance of Docker-based builds, particularly the Alpine-based build in #77?

**Comment by bradlarsen** [comment]
Making the switch to use `mimalloc` as a global allocator so far seems to be easier than I thought -- a simple drop-in replacement, and addition of this in main.rs:
```
use mimalloc::MiMalloc;

#[global_allocator]
static GLOBAL: MiMalloc = MiMalloc;
```

Further performance investigation and validation on various platforms will be required.

**Comment by bradlarsen** [comment]
The performance of using `mimalloc` vs the default allocator in an Alpine Docker-based build is significant: a 5x increase when using 32 worker threads on an Intel-based Ubuntu 22.04 machine.

**Comment by bradlarsen** [comment]
Eyeballing some output from a few runs under `/usr/bin/time`, It looks like peak memory use when running 32-ways parallel on big inputs may also be reduced when using `mimalloc` instead of the system allocator (less heap fragmentation?).

**Comment by munntjlx** [comment]
Thanks for the work on this. For me the 'pull' time saved vs. the few seconds (since its only a single repo) almost makes the non-debian image attractive (even with the 3x slowdown). Since most repos we scan are smallish, and scan times are measured in seconds.

**Comment by bradlarsen** [comment]
@munntjlx I have a branch I'll be pushing and merging "soon", which switches the allocator to mimalloc, sidesteps the alpine performance issue, and seems to all around work. I'm thinking the next Nosey Parker release could provide both the glibc-based Docker image as well as an Alpine-flavored one.

**Comment by munntjlx** [comment]
Great news! Its funny how much difference an allocator can make!

**Comment by bradlarsen** [comment]
This has been merged back to `main`, and `mimalloc` is used in the v0.15.0 release.

**Comment by munntjlx** [comment]
I leave an emoticon with my thanks and gratitude:

😍
