### ISSUE TITLE
Generate manpages and include them in prebuilt releases

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#88]
The prebuilt releases could include man pages generated from the CLI documentation.

See [clap_mangen](https://crates.io/crates/clap_mangen). This would possibly need to be called from the build.rs script. Then, in the `scripts/create_release.zsh` script, we would want to copy those generated man pages into somewhere like `release/share/man/1/`.

**Comment by munntjlx** [comment]
I can help write manpages in Markdown format if appropriate summaries of things are done? Which md2man utility do we want to use?

**Comment by munntjlx** [comment]
Also which 'template' format for MD to make happy MAN pages, there are tons of them, I suspect you want a rust specific one?

**Comment by munntjlx** [comment]
Here are a few of the ones I found, the PANDOC one seems compelling:
https://gabmus.org/posts/man_pages_with_markdown_and_pandoc/

There is also 'ronn'

And a native RUST library:

https://github.com/elebihan/manpages

**Comment by bradlarsen** [comment]
Note, the existing command-line documentation is pulled automatically from Rust doc comments in https://github.com/praetorian-inc/noseyparker/blob/main/crates/noseyparker-cli/src/args.rs, via the `clap` library for CLI parsing.
