### ISSUE TITLE
Fix Docker metadata labels in prebuilt images

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#91]
The prebuilt Docker images for releases do not include all the metadata one would like. See here, for example: https://github.com/praetorian-inc/noseyparker/pkgs/container/noseyparker/137062442?tag=v0.15.0. No labels!

<img width="1054" alt="image" src="https://github.com/praetorian-inc/noseyparker/assets/1483920/657b9486-a5bf-44e2-a286-2499d72549dd">

**Comment by munntjlx** [comment]
You could also include a sha512 sum of the image as a label, version, etc.?

**Comment by bradlarsen** [comment]
I thought I had fixed this issue in c43334c066aa9d048ab465473c439baf5ec5f9d8, but it turns out I did not. I manually re-ran the `Release Artifacts` workflow, and its multi-architecture Docker image still comes out with missing labels!

It sounds like this is a bug or limitation in the [`build-push-action`](https://github.com/docker/build-push-action), specifically with regard to multi-architecture images: https://github.com/docker/build-push-action/issues/846#issuecomment-1546123964

In another project, they worked around this by manually merging the single-architecture Docker image manifests: https://github.com/dbschenker/vaultpal/issues/31

Fixing this deficiency in Nosey Parker will require some more work, probably a manual merge of manifests. It may make sense anyway to manually merge single-architecture Docker images, as the overall Docker workflow could be drastically sped up that way (instead of using qemu to build the ARM64 image, we could use the new M1 macOS runner, avoiding slow binary translation). See https://github.com/docker/build-push-action/issues/846 for inspiration.

**Comment by munntjlx** [comment]
A "fast" way to build a multi arch docker image that I found easier, is simply to use the 2 different build aka x86_64 and arm64 and then just 'publish' to the same container image repo. It should 'just work'. Havent' tried this with non docker repos though!

**Comment by munntjlx** [comment]
Be sure to use the same tag!
