### ISSUE TITLE
Use noseyparker in CI

### ISSUE THREAD

**Issue by Coruscant11** [praetorian-inc/noseyparker#98]
Would be awesome to use noseyparker in pipelines. And also in pre-commit hooks!
For the first, just scanning range of commits only.
For the latest, we need to be able to scan **staged** changes (`git add` content).

What do you think ? Do you have some idea regarding the possible implementation? 😄

**Comment by bradlarsen** [comment]
> For the first, just scanning range of commits only.

One thing that would be desired for Nosey Parker in common CI and pre-commit workflows is the ability to tell it to scan only a range of commits and ignore the rest (e.g., #29). This would let someone have Nosey Parker scan only the new commits in a pull request, for example, and ignore older things.

> For the latest, we need to be able to scan staged changes (git add content).

I have not verified, but I believe that Nosey Parker already scans staged changes.


I had thought of this a bit previously for GitHub Actions in particular; see #26. What CI system do you have in mind?

**Comment by bradlarsen** [comment]
This is a good idea. Closing this issue in favor of #6 and #135; see those for more details.
